modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${display_url}"
credits="${mod_authors}"
authors="${mod_authors}"

# Start of user code block mod configuration
description='''${mod_description}'''
# End of user code block mod configuration

[[dependencies.concoction]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.concoction]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"




# Start of user code block dependencies configuration
[[mixins]]
config="concoction.mixins.json"
# End of user code block dependencies configuration
